---
abstract: 'A generic and consistent interface for online payment services'
author:
  - 'Naveed Massjouni <naveedm9@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300031, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyMerchant
requires:
  Carp: 0
  Moo::Role: 0
  Scalar::Util: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/ironcamel/AnyMerchant/issues
  repository: https://github.com/ironcamel/AnyMerchant.git
version: 0.0001
